# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: jbpm-pvc
# spec:
#   accessModes:
#     - ReadWriteMany
#   resources:
#     requests:
#       storage: 3Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jbpm-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jbpm
  template:
    metadata:
      labels:
        app: jbpm
    spec:
      containers:
        - name: jbpm
          image: jboss/jbpm-server-full:7.35.0.Final
          ports:
            - containerPort: 8080
          env:
            - name: JBPM_DB_DRIVER
              value: mysql
            - name: JBPM_DB_HOST
              value: mysql-service
            - name: JBPM_DB_PORT
              value: "3306"
            - name: JBPM_DB_NAME
              value: jbpm
            - name: JBPM_DB_USER
              value: root
            - name: JBPM_DB_PASSWORD
              value: root
            - name: JAVA_OPTS
              value:  "-Xms64m -Xmx4048m -XX:MetaspaceSize=96M -XX:MaxMetaspaceSize=2024m -Djava.net.preferIPv4Stack=true"
          volumeMounts:
            - name : jbpm-data
              mountPath: /opt
      volumes:
         - name: jbpm-data
           emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: jbpm-service
spec:
  selector:
    app: jbpm
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
