apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-connector-pv
spec:
  capacity:
    storage: 1Gi  # Adjust the size as needed
  accessModes:
    - ReadWriteOnce  # This is suitable for single-node testing
  hostPath:
    path: ./mysql-connector-java-5.1.49-bin.jar  # Replace with the host path to your storage
