apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-connector-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi  # Match the capacity specified in the PV
